import type { AcademyData, Category, MissionData } from "@/types/learnAcademy";

/**
 * Ported from the (now-retired) external Learn app's academiesData.ts.
 * One naming change: "Discovery Academy" → "Science Academy" (id
 * "discovery-academy" → "science-academy") — same content (nature/science
 * exploration), renamed only to avoid confusion with Valiyo's separate
 * Discovery product.
 */
export const ACADEMIES: AcademyData[] = [
  {
    id: "number-academy",
    title: "Number Academy",
    category: "Matematika",
    themeColor: "blue",
    icon: "🔢",
    illustration: "🧮",
    tagline: "Petualangan Angka & Olimpiade Matematika",
    description: "Master numbers through fun math adventures.",
    skills: ["Counting", "Addition", "Subtraction", "Comparison", "Patterns", "Olympiad Math"],
    gradientBg: "from-blue-600 via-sky-600 to-cyan-500",
    cardBorder: "border-blue-300 hover:border-blue-500",
    accentColor: "text-blue-600",
    btnBg:
      "bg-gradient-to-r from-blue-600 to-sky-600 hover:from-blue-700 hover:to-sky-700 shadow-[0_6px_0_#1D4ED8]",
  },
  {
    id: "science-academy",
    title: "Science Academy",
    category: "Sains",
    themeColor: "green",
    icon: "🔬",
    illustration: "🌱",
    tagline: "Eksplorasi Alam & Sains Cilik",
    description: "Explore nature and become a young scientist.",
    skills: ["Science", "Observation", "Experiment", "Living Things", "Earth", "Simple Physics"],
    gradientBg: "from-emerald-600 via-teal-600 to-green-500",
    cardBorder: "border-emerald-300 hover:border-emerald-500",
    accentColor: "text-emerald-600",
    btnBg:
      "bg-gradient-to-r from-emerald-600 to-teal-600 hover:from-emerald-700 hover:to-emerald-700 shadow-[0_6px_0_#047857]",
  },
  {
    id: "world-academy",
    title: "World Academy",
    category: "Pengetahuan Umum",
    themeColor: "orange",
    icon: "🌍",
    illustration: "🗺️",
    tagline: "Jelajahi Dunia & Pengetahuan Sekitar",
    description: "Discover the amazing world around you.",
    skills: [
      "General Knowledge",
      "Animals",
      "Transportation",
      "Community Helpers",
      "Culture",
      "Environment",
    ],
    gradientBg: "from-amber-500 via-orange-500 to-yellow-500",
    cardBorder: "border-amber-300 hover:border-amber-500",
    accentColor: "text-amber-600",
    btnBg:
      "bg-gradient-to-r from-amber-500 to-orange-600 hover:from-amber-600 hover:to-orange-700 shadow-[0_6px_0_#B45309]",
  },
  {
    id: "language-academy",
    title: "Language Academy",
    category: "Bahasa Inggris",
    themeColor: "purple",
    icon: "🇬🇧",
    illustration: "🔤",
    tagline: "Dunia Bahasa Inggris Interaktif",
    description: "Build confidence in English through games.",
    skills: [
      "Vocabulary",
      "Listening",
      "Matching",
      "Reading Readiness",
      "Simple Sentences",
      "Picture Recognition",
    ],
    gradientBg: "from-violet-600 via-purple-600 to-indigo-500",
    cardBorder: "border-violet-300 hover:border-violet-500",
    accentColor: "text-violet-600",
    btnBg:
      "bg-gradient-to-r from-violet-600 to-purple-600 hover:from-violet-700 hover:to-purple-700 shadow-[0_6px_0_#6D28D9]",
  },
  {
    id: "logic-academy",
    title: "Logic Academy",
    category: "Coding Quest",
    themeColor: "royal",
    icon: "🤖",
    illustration: "🧩",
    tagline: "Pemrograman & Berpikir Komputasional Cilik",
    description: "Train your brain like a future programmer.",
    skills: [
      "Coding Thinking",
      "Sequencing",
      "Pattern Recognition",
      "Algorithms",
      "Problem Solving",
      "Robot Navigation",
      "Computational Thinking",
    ],
    gradientBg: "from-purple-800 via-indigo-800 to-fuchsia-700",
    cardBorder: "border-purple-400 hover:border-fuchsia-400",
    accentColor: "text-purple-700",
    btnBg:
      "bg-gradient-to-r from-purple-700 to-fuchsia-700 hover:from-purple-800 hover:to-fuchsia-800 shadow-[0_6px_0_#4C1D95]",
  },

  // Future Ready Expansion Academies (coming soon in the source app too)
  {
    id: "creative-academy",
    title: "Creative Academy",
    category: "Pengetahuan Umum",
    themeColor: "orange",
    icon: "🎨",
    illustration: "🖌️",
    tagline: "Seni & Ekspresi Kreatif",
    description: "Unleash imagination through art, colors, and shapes.",
    skills: ["Drawing", "Color Theory", "Shapes", "Design Thinking"],
    gradientBg: "from-pink-500 to-rose-500",
    cardBorder: "border-pink-200",
    accentColor: "text-pink-600",
    btnBg: "bg-pink-400 cursor-not-allowed",
    isComingSoon: true,
  },
  {
    id: "music-academy",
    title: "Music Academy",
    category: "Pengetahuan Umum",
    themeColor: "orange",
    icon: "🎵",
    illustration: "🎼",
    tagline: "Irama, Lagu & Pengenalan Musik",
    description: "Explore rhythms, melodies, and sound harmony.",
    skills: ["Rhythm", "Instrument Names", "Pitch", "Melody"],
    gradientBg: "from-amber-400 to-yellow-500",
    cardBorder: "border-amber-200",
    accentColor: "text-amber-600",
    btnBg: "bg-amber-400 cursor-not-allowed",
    isComingSoon: true,
  },
  {
    id: "ai-academy",
    title: "AI Academy",
    category: "Coding Quest",
    themeColor: "royal",
    icon: "✨",
    illustration: "🌌",
    tagline: "Dunia Kecerdasan Buatan Cilik",
    description: "Understand prompt logic, machine vision & smart thinking.",
    skills: ["Prompt Logic", "Image Recognition", "Smart Bots"],
    gradientBg: "from-cyan-600 to-blue-700",
    cardBorder: "border-cyan-200",
    accentColor: "text-cyan-600",
    btnBg: "bg-cyan-400 cursor-not-allowed",
    isComingSoon: true,
  },
];

/**
 * The same 6 generic mission templates apply to any academy/category —
 * ported as-is from getMissionsForAcademy(). Gameplay for these ("Mulai
 * Misi") lands in a follow-up milestone (the quiz/coding-quest engine);
 * for now they're real, correctly-priced mission cards shown as
 * not-yet-playable rather than fake fully-wired buttons.
 */
export function getMissionsForAcademy(category: Category): MissionData[] {
  return [
    {
      id: `misi-easy-${category}`,
      type: "easy",
      title: "⭐ Misi Jelajah Ringan",
      description: "5 soal latihan cepat untuk pemanasan otak!",
      starsReward: 15,
      questionCount: 5,
      estimatedMinutes: 3,
      difficultyRating: "⭐ Mudah",
      badgeIcon: "🌱",
      isUnlocked: true,
    },
    {
      id: `misi-normal-${category}`,
      type: "normal",
      title: "⭐⭐ Petualangan Standar",
      description: "10 soal petualangan seru untuk memperkuat pemahaman.",
      starsReward: 30,
      questionCount: 10,
      estimatedMinutes: 6,
      difficultyRating: "⭐⭐ Sedang",
      badgeIcon: "🛡️",
      isUnlocked: true,
    },
    {
      id: `misi-challenge-${category}`,
      type: "challenge",
      title: "⭐⭐⭐ Tantangan Master",
      description: "15 soal penuh teka-teki logika untuk menguji ketelitian.",
      starsReward: 45,
      questionCount: 15,
      estimatedMinutes: 10,
      difficultyRating: "⭐⭐⭐ Menantang",
      badgeIcon: "⚔️",
      isUnlocked: true,
    },
    {
      id: `misi-olympiad-${category}`,
      type: "olympiad",
      title: "🏆 Simulasi Olimpiade Resmi",
      description: "20 soal standar Olimpiade Anak. Raih medali emas!",
      starsReward: 60,
      questionCount: 20,
      estimatedMinutes: 15,
      difficultyRating: "🏆 Kompetisi",
      badgeIcon: "🥇",
      isUnlocked: true,
    },
    {
      id: `misi-daily-${category}`,
      type: "daily",
      title: "🎯 Tantangan Harian Spesial",
      description: "10 soal pilihan hari ini dengan ekstra +20 Bintang Bonus!",
      starsReward: 50,
      questionCount: 10,
      estimatedMinutes: 5,
      difficultyRating: "🔥 Bonus Harian",
      badgeIcon: "🎁",
      isUnlocked: true,
    },
    {
      id: `misi-ai-${category}`,
      type: "ai_quest",
      title: "🤖 AI & Quest Interaktif",
      description: "Misi interaktif dengan feedback visual dan audio real-time.",
      starsReward: 50,
      questionCount: 10,
      estimatedMinutes: 8,
      difficultyRating: "⚡ Interaktif",
      badgeIcon: "🤖",
      isUnlocked: true,
    },
  ];
}
